### PR TITLE
added check to see if vm is already registered. This ensures register…

### PR DESCRIPTION
**Pull request by rasmuschristensen**
… can be called when app resumes. If you open an app on android etc. then uses the back navigation you get the homescreen. Then you resumes the app and it will crash, because it tries to register the vm's again. I've added a check to see if the vm type (the key) is already registered, and if so just ignores the registration for this type.

### CODE REVIEW

**Comment by codemillmatt** [comment]
Thanks Rasmus! I'll run this through and should get it merged and pushed to NuGet soon!

**Comment by rasmuschristensen** [comment]
I used visual studio 2017 and I guess you used vs4mac/xs. I can see I got the project file updated too. Sometimes deploy/run configuration is not enabled in visual studio when the project is created on the mac. So this is also included.

**Comment by codemillmatt** [comment]
Thanks Rasmus. I'll be taking a look this weekend - I'll let you know if there's any questions.

**Comment by rasmuschristensen** [comment]
Btw. I was wondering if we should add a Test project :) a fix like this would be easy to verify. What do you prefer NUnit, xUnit or something else?

**Comment by codemillmatt** [comment]
Merging everything in - closes #13

**Pull request merged**
